### PR TITLE
Fix /apis endpoint

### LINKED ISSUE #149: Incorrect /apis endpoint
The `/apis` endpoint implemented by [ApiResourceController.java#L42](https://github.com/zalando-incubator/api-discovery/blob/master/storage/src/main/java/org/zalando/apidiscovery/storage/resource/ApiResourceController.java#L42) does not match the API definition at [api-repository-api.yaml#L107](https://github.com/zalando-incubator/api-discovery/blob/master/storage/src/main/resources/api/api-repository-api.yaml#L107).

* Instead of a list of `ApiMetaData`, the returned ApiList object contains a list of `Api`.
* `ApiMetaData` lacks the `id` property.

### PR DESCRIPTION
**Pull request by mfellner**
Closes #149.

* ApiList.apis is now a collection of ApiDefinition
* ApiDefinition 'name' was replaced with 'id'
* Api definition file was updated

### CODE REVIEW

File: storage/src/main/java/org/zalando/apidiscovery/storage/domain/model/ApiList.java [hunk 1]
```diff
@@ -13,6 +13,6 @@
 @Builder
 public class ApiList {
```
Comment (maschleg) [inline storage/src/main/java/org/zalando/apidiscovery/storage/domain/model/ApiList.java]: please rename this ``Apis``we aligned on using plurals instead of List suffix.

**Comment by fmueller** [comment]
👍
